# Site settings
author: Christopher Morgan
title: Becoming a Full Stack Software Engineer
header-img: img/home-bg.png
email: cwm111794@gmail.com
copyright_name: Christopher Morgan
description: > # this means to ignore newlines until "baseurl:"
  Coding Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chrismorgan1117

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
